// Code generated by mockery v1.0.0
package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

// DispatchAccessed provides a mock function with given fields: _a0
func (_m *Dispatcher) DispatchAccessed(_a0 context.Context) {
	_m.Called(_a0)
}
